title: Academic Reviews
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
markdown: kramdown
