title: Academic Reviews

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-toc
  - jekyll-analytics
  - jekyll-scholar
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
  - jekyll-assets
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
markdown: kramdown
