title: Academic Reviews

plugins:
  -plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-toc
  - jekyll-analytics
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
markdown: kramdown
